[python]
dependencies = [
  "pandas",
  "gpxpy",
  "shapely==2.1.1",
  "rtree",
  "networkx",
  "scipy",
  "scikit-learn",
  "numpy",
    "rasterio",
    "geopandas",
    "fiona",
    "elevation",
  "pyrosm"
  , "tqdm"
  , "tiktoken"
  , "openai"
  , "pyyaml"
  , "matplotlib"
]

[deps]
rocksdict = "*"
